
˛∂
Æ
$ref_AppliedPTransform_WriteToText_10Ö
T
#beam:transform:generic_composite:v1-<WriteToText(PTransform) label=[WriteToText]>*ref_AppliedPTransform_WriteToText-Write_11%
Noneref_PCollection_PCollection_5"&
Noneref_PCollection_PCollection_16*WriteToText:%ref_Environment_default_environment_1
ı
Aref_AppliedPTransform_WriteToText-Write-WriteImpl-WriteBundles_20Ø
ù
beam:transform:pardo:v1Å
¡
 beam:dofn:pickled_python_info:v1úQlpoOTFBWSZTWf9yBHEAAWN/4F+9e+BWd94SPWndgr/v3+JixA4AQAHdLDTIaCVD0GpiPRMaajR6QaepkPaiDR6gAek2pkAMNAVMwlPEptomKe0U9IPUGgDIMjTIA9QANDhoZNNDTI0NMjIMjI0MgMTRk0AZMjEMJJEiZ6kepk09IaBpoAGgABoGgA8oBtRzK5+u1HL5ZAdjAzDMJhhW1fzUyh4eo+Rgo4F4bUHjFu+Ho66DLGZmqux31mF4qDdSNGtJz/ilqMRD3qZSAxJT0FJHPLg65VnS3+Lkogm9EekwIbdkIIUSI4SNazwyMDND2FZi94qPlMqAnhXOUu3bNYUlKOrHiHJamrlQTk+WVLgzjjvy2Rp7VZZJVS3AtCZkSOiUIk0h0obtVwLEFZzdjN7gULTY6dZrBwZgjebg12mpbJJO0LiHjtwlIbqd3nrzc5+vmw4QVwKNRm2LfErBnYPkuQ5bevf0x8tkmKiAqqG8J0fPRotzhfuhXV44ARe9QRluBCU14Jk8AN56FMg7IAsAuKJjEMzoXTKa4LShgrvrjUP1J+/hqifo6wJ75J8wVOR0fWc6ReyLgBWRLa32MZ21IplSZDULVnpDz7HNqtLvdWja1U6nCIn5x1og7OWx8OXraXFIxxVSrtiVi0mC82akXB7R2ghALM1iqsJqlMfW33lgJDVpgQwwg0LwnImYy5XGLfcHE1BnMhnN0vHsgPwJ0R4/3FbJyedtdFFkMBCD/69J5YLmGlg7EmtodE2i0ra8EHwHSajZ/xdyRThQkP9yBHE=∫
;python_side_input0-WriteToText/Write/WriteImpl/WriteBundles˙

beam:side_input:iterable:v1å

#beam:view_fn:pickled_python_data:v1‰	QlpoOTFBWSZTWR0QNR0AAij/8////y56Z4slD6tdgP//37f71A4EYAAAQBAIAAHAAxbnKR0RddhqaEU9NPSmGpiGNE2k002oGg0ZGhoZNANGjQAyZANA1NKYKflMNE1HqPTU0MmhoA0eoAAAAAA0eoNAAgJU21T9U0NMhhGQNNAxGBAxAaABoaGCNBhlDCU0giE8qb0k8mTQTTRoNNqaGjR6gNNAAAAA0AAXIUCyAItTp5M4TLiRfbAaYFexQeo28cM36k3kgGU+9BbCF2BjbFj+eBsb90BpeI871qBbEIMYwMcf5lopQGRA8WYoDRsfZDYlBBMd2MxMUIktNYHTtJePaXO9tVZH1xr9Z5L06Y03KNotM/5hkPzjRYm/SOmgJV7u57vfWpOOyooeI5by/hyRG7sfUjzKxOurQBdiw7jQDmriKc3qSYErQB+OSg9w6XhNXC/PwIDBYK7yAYKUCvt14OfYoWSlKC5jbUuWjIrec6lxXRYYh9newMyoy1sF47l7L1tWWNnvjchZK8MWnk2feJpjVWBx6C9KtWui2vGDY7mgqNCvQYhnywNTNsB4p99CErezKAAU8JAt39tAWEJFOjT00EMxcWSaKbFfxahzgGxXicgmMlk7mA55OTIoHrTmqNKCkQyxqChZ/G1rZqGlQPduF2NQUCQxscW1QECavj3LHmng+ffqwosF6FfMD52jGGp0Mjjovo1kD3RuXhhdOpgzvPmYiBRhR80LSu/TfMktAt4qWMfCsla11tJfrIZVJEZNI1g55TqDFW/NFRnyXyap0QzBKy5IZBmwQMsKB3kUiDApcSZDtOaJS6Kbc2Z4OG7IgQjJk2zFYqgyYGZMZ9b0VGPKz3nBoWca3bqN/bI6LNIujfCe2IjFt4PjNDaSgama07DNtQrJa0CwslineU1eEFwg4x0FkhtDlwTIs0zU4RQjtSU0l04FRZpROEyqzlvlmlKGVCJxE4A7boIzBB6SmsNWF+fSBWiW2A3AEJcDiY67kvGCnNOz3Y2gYqjd3HAIHgy+dRE2/sOIAIj7rCGId5kHlJITcycVbdUdM093QNFDeD/ZmmzUcu3WIULVo36G+y3JuzbaClDMJRASXEQs8kQ0JHRgZnEIBwiEBum5Ctg+cUIuNOm9OktTkUidIiUFP4duGGFfu0hrkkY5cOOvGqanlRynciTRSwU5OdUZQ+0mWGzqaYZbJJn5KJlK6CmfroUViRhdwyZn9gF3JFOFCQHRA1HQ…
(beam:window_mapping_fn:pickled_python:v1úQlpoOTFBWSZTWZSnr4UAACJ34EwAACAgAQgAAAC/596AQAQOACAASIp6mj1Bppk9TIHtU0FNT0jTQ9CYQNPTRDImBd0r8s9K9NNArxThgM2Te+1nSjF6nhKFjgpkLgI+ZCbAu3QmeGCU2TAu5IpwoSEpT18K&
Noneref_PCollection_PCollection_10\
;python_side_input0-WriteToText/Write/WriteImpl/WriteBundlesref_PCollection_PCollection_9"&
Noneref_PCollection_PCollection_11*(WriteToText/Write/WriteImpl/WriteBundles2Ñ
beam:display_data:labelled:v1c
Transform Function&apache_beam.io.iobase._WriteBundleDoFn2fn:!apache_beam.transforms.core.ParDo2b
beam:display_data:labelled:v1A
compressionauto2compression:apache_beam.io.textio._TextSink2±
beam:display_data:labelled:v1è
File PatternPgs://cloudcomputing-345522-gs/output/predict-%(shard_num)05d-of-%(num_shards)05d2file_pattern:apache_beam.io.textio._TextSink2o
beam:display_data:labelled:v1N
Append Trailing New Lines2append_newline:apache_beam.io.textio._TextSink:%ref_Environment_default_environment_1
Å
\ref_AppliedPTransform_ReadFromText-Read-SDFBoundedSourceReader-ParDo-SDFBoundedSourceDoFn-_7†
ÿ
beam:transform:pardo:v1º
°
 beam:dofn:pickled_python_info:v1¸QlpoOTFBWSZTWSYnam0AAzf/+P//3/9EZ591P//fgr//3/f/5A4AYAAAEAAA0AQt5g3I7kdzKqBokyaTRM1NpHlGmJqegATyjTGgnkBqbUH6hMMU8UfpQGjTA0BkpTz1RPJonqPFGhoAAAAaMgBkAAAAAADQBpogQRpPUj09TFHqaGR6m1NDJoANAABoAAAZGgA0OAANAADIAAADIaNAAAAAAAAABKagSno1Nkp+ianqHqNNDQGmnqHqAaNADQAAAA2kDQHqFmGAcbZ2AXv44a536vIQrExfOUGyXc6VSBUGMhZd3+afbUoazKRa2We5QHPubFDxEuIIEPjrzPQVYNlkGDCqJOUEkAkzEkDxCEzIQarhyEhCFrez148erKtYcixveYRAW0YkGmy+oIKjLrq6lvq61N0KrA9vmLNAUcaBiuyLGUlbWP+eNyCOMb4upgd/Y4pEQrFvZtENyqKYM8+nzIdRwKIUuBU7Wjw27ZDfnlKu4rcL2H+oKenX1ismlCEolsJTheuGz1zc+7em6gSpL4a/4ZMVgKxcIDKgDBgr0f7t4AimMipxXp5RQBQMixXz+BWWgHKMflIVM4WqTxxFvHguiIj2tCTg18qH6o0NXSO19OnacDhmAH5+ZBL2PVVuTNs2pEWNcMcPILDUo5LKsBEmt+xmSfDLEAtt6Bu7QEEhqRqocNftq8AG0hnKezcp7vhi3F8KRLkz4I5VpXYKjCpyz6eskxABPvau4UlY5CKwJKMACKhfshRTm3+2BVMgkOWt+pMZZCTn3nGyGnGQiAIgYFmccK2SmAuC1NRd3+dDQwFFMNUAReC3lW9mAApIIZ52lU6E0pSuYZ51gGAxFCUpEVMhb7KBUJGVOIjiNqUUTX/NAiYVlqIOIg9TkCYbUWViIvTC7KlLA2nP48GbxShzGNR4PEL0uchscknXQK6B+1u7CUAnCgN48108jGkfgwAgC+A9QmAh7CcJFmbLZE2UvobGEwn04ac0ruXLJYMMsgAzAcCNDTkDISW9RSmcVWTOzSey3zoJYQ7CosRyMwsnK56HjEcLoInIQaRGLwvrAmJr3OlZGsRUkQUIOHiJ0CgovRYnTnPC81Dmuy8VIIOGVOeSegLyCRButtyua9QdxjaMXhcKy2VQVilmAaPJv9MLSYqamGKgwIkLqM1ljKLQRBhvNnPZHuy6AJsowQvh7VmsVrcYICRQouCWYOape55IKJAoeZTdYuGMHaSrUWDHk3xG9kpkhnoUiQgsNuRWovZmzxb/LpsuDSgKp3rEpq0GD8GbPn5bMWr9iJui4WCkYeqCoJgwSmEjYoxcaz8Wcz6imy8450E1uRv4Fot1aEzGhqXHgYL1OeE8aj7RxQTCBO+IxsgIKTPLrQG4Tz7vO+7DCKeM0gMhE7xTboWQzkBmsE3AeBgk2VrunUQTIEHq/gf1npNFEEl7+TvDO/ZcwVKyjW+oCWEimJ4Ueoo8zkOjU0mxGUxEWm5pWnBcEAdvIe3OTBsi/GIRdHCmyU7nRWFOlfOAEKCGJfKcLoUNnNSIiWmIAvz1tB1mk7IxwaSrNK6Y5QSkj/GSO0Zq1oiKqZaNDMFnjClSHudrLVPGwmSxp2tL5rdMScpZWK7k1khmKkZt/SvEneLs8H/i7kinChIExO1NoA==:ref_Coder_TupleCoder_4%
Noneref_PCollection_PCollection_2"%
Noneref_PCollection_PCollection_3*DReadFromText/Read/SDFBoundedSourceReader/ParDo(SDFBoundedSourceDoFn)2à
beam:display_data:labelled:v1g
Transform Function*apache_beam.io.iobase.SDFBoundedSourceDoFn2fn:!apache_beam.transforms.core.ParDo2ô
beam:display_data:labelled:v1x
File Pattern.gs://cloudcomputing-345522-gs/input/images.txt2file_pattern:*apache_beam.io.iobase.SDFBoundedSourceDoFn2r
beam:display_data:labelled:v1Q
Compression Typeauto2compression:*apache_beam.io.iobase.SDFBoundedSourceDoFn2x
beam:display_data:labelled:v1W
Strip Trailing New Lines2strip_newline:*apache_beam.io.iobase.SDFBoundedSourceDoFn2j
beam:display_data:labelled:v1I
Buffer Size(Ä@2buffer_size:*apache_beam.io.iobase.SDFBoundedSourceDoFn2É
beam:display_data:labelled:v1b
Coder&apache_beam.coders.coders.StrUtf8Coder2coder:*apache_beam.io.iobase.SDFBoundedSourceDoFn2Ä
beam:display_data:labelled:v1_
source!apache_beam.io.textio._TextSource2source:*apache_beam.io.iobase.SDFBoundedSourceDoFn:%ref_Environment_default_environment_1
Û
4ref_AppliedPTransform_WriteToText-Write-WriteImpl_12∫
P
#beam:transform:generic_composite:v1)<WriteImpl(PTransform) label=[WriteImpl]>;ref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce_13Dref_AppliedPTransform_WriteToText-Write-WriteImpl-InitializeWrite_18Mref_AppliedPTransform_WriteToText-Write-WriteImpl-WindowInto-WindowIntoFn-_19Aref_AppliedPTransform_WriteToText-Write-WriteImpl-WriteBundles_209ref_AppliedPTransform_WriteToText-Write-WriteImpl-Pair_21?ref_AppliedPTransform_WriteToText-Write-WriteImpl-GroupByKey_22<ref_AppliedPTransform_WriteToText-Write-WriteImpl-Extract_23@ref_AppliedPTransform_WriteToText-Write-WriteImpl-PreFinalize_24Bref_AppliedPTransform_WriteToText-Write-WriteImpl-FinalizeWrite_25%
Noneref_PCollection_PCollection_5"&
Noneref_PCollection_PCollection_16*WriteToText/Write/WriteImpl:%ref_Environment_default_environment_1
ƒ
Dref_AppliedPTransform_WriteToText-Write-WriteImpl-InitializeWrite_18˚
–

beam:transform:pardo:v1¥

±

 beam:dofn:pickled_python_info:v1å
QlpoOTFBWSZTWTVqZWQAAkx/8H//e2jWd941HWvdgr//3/5jxQ4AdABQAy6Dus22rXNoSpkmiCn5NT0Ejwpp5NQzUG1B6nlPQI9Q9R7SnqNHqNHqep5TEGgNTRNNU8xGqeRPKepoAaDQAANAAAAAAAAaJM0mqek0emmk00yAD0Q9QAAAAAAAGgBoNPUpqjag0Gg00aaAAAGgGmgAAAAAANDhiNNNBoA0AAAANBkGmgaADRoAxDQORniDp+2Hnllf4jov9L39zO/aL/oShAxzVURD3p0c6nIhQYhIEqwSTjJAmQwgTjSCICez/12TjKYCtc5dI9ezqwn9SQvTdngwUvkcR9I42IaEcKo2h6VPMj4S5oJmsf1H1Mg/1mSZNJVotllZKQ7drRJgu+v0PzJhqmdmtxu3MPgLWUV5ODha7HPXkEbbYiR63moGeOJoAkPj7VSTTj5Z15IWXMdefmrLAwJ0vthtw2MkU2akSPIZcsN8ePKq008LEbIPjbqPJsVm4NYw3H9ZcchkxacLIAH4QgOvumf45+MowbIxZ1fJuxNKOi436Qa2MS0SNiADOkWJbV+a1z4IQ4Q6a11XDkfgNDUJPhXsjJbSksxYsIJWciYyqeIMM8lonGUmcSihx3WwAfQzQLeNFmfwkQAcT7jUhqlO0BsEBkKoUiUEHCu1o8UFUgioNTqyD0dUlp1MKBCIdy/sFce3rC4tFINs4b6gqM7abqb/sVleQYu0BDNqVGkdkmlNLAlkulGusTpFrdthhK2l1ctLDbtVtYSgoFGIWNzIIpAyca74SL7vPEK1IUUhGQtDNiqdvHNWgEAaoAGU4KqgyYei55YYDJoPznNQY9AKwbtG8+VByJBqVnfxRDSHDGxLXdKw8IHzMt3jCogC3oc2ivGFqmAEQm9zXIJgIxoaJbAIUjFPHPLLnykVXPiHMs4YlRkTFaCdhAac0xqIhMEBLZTaiJIRdA9ZgSPLlvKRsezsgsLGw+6MKcpRE1LyPegpkPPDFeuREVCpJUYxYUp+8pzLNjCidHFCJwDRPaGmCy+YGJiCoEEJXAMwl3rQCikAXAEiOnXeGzPKRps8sNoMRG9ogoUs/XjeWylFpKtWUUQlTCc6xJe5slOYEt2jGj9XcZZYFuSAL4UBAoQd4nW4MoCauEy9qX2y/XSOlf/aJiQg5H7DrBG88SlEbYHCBV7KsBchyvFNdYKAw1wfjI576/X/GUcQLZBYQvmbEgsEQqQ5QfLExGqdHIlb0rkqnrQJEbIDUeVbxnxf4u5IpwoSBq1MrIA=%
Noneref_PCollection_PCollection_8"%
Noneref_PCollection_PCollection_9*+WriteToText/Write/WriteImpl/InitializeWrite2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2t
beam:display_data:labelled:v1S
Transform Function<lambda>2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
®
Mref_AppliedPTransform_WriteToText-Write-WriteImpl-WindowInto-WindowIntoFn-_19÷
ô
beam:transform:window_into:v1x
"
 beam:window_fn:global_windows:v1ref_Coder_GlobalWindowCoder_2": (08HZ%ref_Environment_default_environment_1%
Noneref_PCollection_PCollection_5"&
Noneref_PCollection_PCollection_10*4WriteToText/Write/WriteImpl/WindowInto(WindowIntoFn)2ã
beam:display_data:labelled:v1j
Transform Function(apache_beam.transforms.core.WindowIntoFn2fn:&apache_beam.transforms.core.WindowInto:%ref_Environment_default_environment_1
œ

"ref_AppliedPTransform_Prediction_9®

∞
beam:transform:pardo:v1î
ë
 beam:dofn:pickled_python_info:v1ÏQlpoOTFBWSZTWWfz/6gAAY5/+P//VWhPZ/8cD2vfBr///2Zqhw4AYAAAgAABQAJWYygxDUNIApp6EHlD1HqbU0BoBtIHpNDRk8o09QPU00AADRAjU0bRPQCTamJ6SPRDQ0Gj1NABoAAGnqeiGgNTEykanoENA0wgZAGgAAAA0AAGgbUHDQAA0Gg0BggBoaaZANDRpkAMQNACTDzf1B0egPf5uawM4i0pFcWGapz6bPJr1ej7g0lMg1E90DuS1dSeIRRzLyY/qIAx8FKpG8gHrQayQViczVFks9gGJCMkVkCuJVRHT3r/WFAImW3SEgICcTogYOxW3UWsjQQsZLh/0xlDxHWdjvcE/oLV8MPc0657fKxbLtoXMa7cwlpFWg1l1opCsQZLdeWbAKjvFr4b8qS3qS2jeXCnWZB2EWpmiAFOGi3Ni1uelQDM8QwC/JHmHlTCq4Zd3ou7mwoqbEDZGI7wSCVSB5CHfA1a4A4J9vuUSRU+IkXhxiSDI7xpe0uIOPaGUaLbQ0R6+GXAZLGCU5TSr5ow12d9MW8MawYuGIlMQ0w09UM2xAUUHiOKqjC49TWEBxLhBllemT21FlQPiCPwr1Qc8Hj3EHTP0RUfz7SsMZ6KMUwOzdzF2dvgywbGyJFgnPCJ1xyz5TwItDcrUwQCE2oChAGpWxFQnYymEkywpuMNMFeBq7TT+gwYb+mIcZvjrfGZZ9C742urMOUEJq929ZuXX9kzf0snBjZaicqtRiNRIPNyX23C9olEl2dYtB0tGZCUnzR7k7MVAMDGBkQmelahZhAz70wUYnMUDTD60OjdTgKGTfdCvbrrFpCENqycrCBmTL8B8++omWk/CpHXLGmqaOapCcE2pQOnRgEBPcHKTrOgYIg4TiUnIZmQAVAYD8s3D6fGLsd85UtG8VUfGRAjTEbBFdDRsN6QRrTEqR4iq9bYQtiqshjCnEsVaWI46sMuKFz45DY9cMagYqoGbn/7y/8XckU4UJBn8/+o%
Noneref_PCollection_PCollection_4"%
Noneref_PCollection_PCollection_5*
Prediction2r
beam:display_data:labelled:v1Q
Transform Function__main__.PredictDoFn2fn:!apache_beam.transforms.core.ParDo:%ref_Environment_default_environment_1
Ì
@ref_AppliedPTransform_WriteToText-Write-WriteImpl-PreFinalize_24®
¿
beam:transform:pardo:v1§
ç
 beam:dofn:pickled_python_info:v1ËQlpoOTFBWSZTWYZErMAAAYb/4F/+eyhff94QPWndgr/v3/JixC4AQAIdLVsaaGhEp6ZqjanqGnqeoek9TT1ND1GTTQ8oGjQAPUPUAB6g0mRU2NT01E8p6QAyGjIADINBkGQAYjQDjQ0DRpkaaNMgMTBAADQGgNMgMCZAxEKYQp4ZFMyh5E/VHqANG1ABoeo0A9NEaNDRke/zN/GPKgfeiCkSAlYW/2YoCj56xphuICaadcIkj7NmXr73niMvAzMKVXmvqpF4mT5MyTzlWuPGlMC6JXywgywvtKJHe27zUN0O3p1kU3Il2/WUw1HuWggkRN2BJCNcFgPrULBxE5IZYSGr6cZkTACWMekcHr4M0sINzapvYJVDz8dQaReqDUV7IxRFuUx0W82gtsKbTyy2ugcEgOUzhptiJGiVs+ImVQjCtSglLETavzNFNoTqeISBUY4IhQ1rHA7M6ejsMgXSEnHKYESoxMe/ejDyu3bySNBZBFE5SlzVQ2gIlhqFcCjpljsjxuMWT7gdDsJ4h+WglnRiC/ZGzONMx6FoCiMnJRxhi6fftiKUZwNtmQELUHAh0xY+BakLOK6Ht9A71gyuIijI4+rnJhp7Wm4KJVk1co6iyhAz7chJ1u+JrtAzxyuOSM4NupF32MBagN1nRmRHXGGmFvcEqX2d2lRKaCAcq3McwTwZ4aTjMa710cqrosE4TQohPZHET1rUD6tqYd0vdzAUZ6QMVd43FTOHv6XFYGcaJwByPfAip+EliN/pMNiFf9TDQt5SX4QLumIZAMzAc6AHMB9VEMjP+2rYjqFS6m4NRTlhiiDG8a0ld1xUQNS0BmlvTCTzUxZ712MoRXOnOr/i7kinChIQyJWYAA==’
:python_side_input1-WriteToText/Write/WriteImpl/PreFinalizeñ

beam:side_input:iterable:v1®
#beam:view_fn:pickled_python_data:v1ÄQlpoOTFBWSZTWevwyHMAAIR/4HTzUAAAY4glCgscAL//3yZDBA4AMADERBNIE9IGmj0T0QNNA0yAeoMg1NAgxJoZPUBoaAAaBpoBgAAAANAAAAABEKw87hknW4MTzjfogD5DPaKy3zV2GnwgNjXOMXa6iapkp5GSSkgItRcCEUzRwNBAbeeI6KaXrHia0WtPQCg11VmpXmk4omI1aFZ06Gyruk5DfTphvCYxdhR6NeiccmyFVRSQrDGQ2jMiSN71Qwd3W42PDSUICNOlJ1nwIXU94W6dg72CCSkic6IpwhWNSMROaTJVxBQua6lid9kkwsYcVxzFkBgh5B0IxH5cdp/rUpvhcCHRzixdLIXSlJ/NBAUf8XckU4UJDr8MhzA=…
(beam:window_mapping_fn:pickled_python:v1úQlpoOTFBWSZTWZSnr4UAACJ34EwAACAgAQgAAAC/596AQAQOACAASIp6mj1Bppk9TIHtU0FNT0jTQ9CYQNPTRDImBd0r8s9K9NNArxThgM2Te+1nSjF6nhKFjgpkLgI+ZCbAu3QmeGCU2TAu5IpwoSEpT18Kπ
:python_side_input0-WriteToText/Write/WriteImpl/PreFinalize˙

beam:side_input:iterable:v1å

#beam:view_fn:pickled_python_data:v1‰	QlpoOTFBWSZTWR0QNR0AAij/8////y56Z4slD6tdgP//37f71A4EYAAAQBAIAAHAAxbnKR0RddhqaEU9NPSmGpiGNE2k002oGg0ZGhoZNANGjQAyZANA1NKYKflMNE1HqPTU0MmhoA0eoAAAAAA0eoNAAgJU21T9U0NMhhGQNNAxGBAxAaABoaGCNBhlDCU0giE8qb0k8mTQTTRoNNqaGjR6gNNAAAAA0AAXIUCyAItTp5M4TLiRfbAaYFexQeo28cM36k3kgGU+9BbCF2BjbFj+eBsb90BpeI871qBbEIMYwMcf5lopQGRA8WYoDRsfZDYlBBMd2MxMUIktNYHTtJePaXO9tVZH1xr9Z5L06Y03KNotM/5hkPzjRYm/SOmgJV7u57vfWpOOyooeI5by/hyRG7sfUjzKxOurQBdiw7jQDmriKc3qSYErQB+OSg9w6XhNXC/PwIDBYK7yAYKUCvt14OfYoWSlKC5jbUuWjIrec6lxXRYYh9newMyoy1sF47l7L1tWWNnvjchZK8MWnk2feJpjVWBx6C9KtWui2vGDY7mgqNCvQYhnywNTNsB4p99CErezKAAU8JAt39tAWEJFOjT00EMxcWSaKbFfxahzgGxXicgmMlk7mA55OTIoHrTmqNKCkQyxqChZ/G1rZqGlQPduF2NQUCQxscW1QECavj3LHmng+ffqwosF6FfMD52jGGp0Mjjovo1kD3RuXhhdOpgzvPmYiBRhR80LSu/TfMktAt4qWMfCsla11tJfrIZVJEZNI1g55TqDFW/NFRnyXyap0QzBKy5IZBmwQMsKB3kUiDApcSZDtOaJS6Kbc2Z4OG7IgQjJk2zFYqgyYGZMZ9b0VGPKz3nBoWca3bqN/bI6LNIujfCe2IjFt4PjNDaSgama07DNtQrJa0CwslineU1eEFwg4x0FkhtDlwTIs0zU4RQjtSU0l04FRZpROEyqzlvlmlKGVCJxE4A7boIzBB6SmsNWF+fSBWiW2A3AEJcDiY67kvGCnNOz3Y2gYqjd3HAIHgy+dRE2/sOIAIj7rCGId5kHlJITcycVbdUdM093QNFDeD/ZmmzUcu3WIULVo36G+y3JuzbaClDMJRASXEQs8kQ0JHRgZnEIBwiEBum5Ctg+cUIuNOm9OktTkUidIiUFP4duGGFfu0hrkkY5cOOvGqanlRynciTRSwU5OdUZQ+0mWGzqaYZbJJn5KJlK6CmfroUViRhdwyZn9gF3JFOFCQHRA1HQ…
(beam:window_mapping_fn:pickled_python:v1úQlpoOTFBWSZTWZSnr4UAACJ34EwAACAgAQgAAAC/596AQAQOACAASIp6mj1Bppk9TIHtU0FNT0jTQ9CYQNPTRDImBd0r8s9K9NNArxThgM2Te+1nSjF6nhKFjgpkLgI+ZCbAu3QmeGCU2TAu5IpwoSEpT18K%
Noneref_PCollection_PCollection_8[
:python_side_input0-WriteToText/Write/WriteImpl/PreFinalizeref_PCollection_PCollection_9\
:python_side_input1-WriteToText/Write/WriteImpl/PreFinalizeref_PCollection_PCollection_14"&
Noneref_PCollection_PCollection_15*'WriteToText/Write/WriteImpl/PreFinalize2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2y
beam:display_data:labelled:v1X
Transform Function_pre_finalize2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
∑
Cref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce-Impulse_14p

beam:transform:impulse:v1"%
Noneref_PCollection_PCollection_6**WriteToText/Write/WriteImpl/DoOnce/Impulse
	
[ref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce-FlatMap-lambda-at-core-py-3228-_15ê	
Ã
beam:transform:pardo:v1∞
≠
 beam:dofn:pickled_python_info:v1àQlpoOTFBWSZTWYeBadMAAPz/4H39eAhAY4hnDWucgr//3zJjxA4EMAGaKbENTQJqehMJpp6p6nkjJpoPU0AANqPU09IACKelPFHqZ6oaA9IBoaAAAAAAADTSBKbCaj1DJpoM0hpoABoaA002o0PUUpSPvsxPvhyaMcStzrEgKBKyiQLCP5JCmOnyyhnoHICBza++t62HhpP4ZIc4V66os1OzWRxecXIWEQFOgdZAwZ2wBGJ4R3BQEteix28pdZDRoahwOPMOfPluApux3V54TMzLHR09iFLMeOKqDXwJNv4zyoA5X4almbIp4skbWMoJryo5InOMeJHhoMqQR7aolzSLhzttNDAdKVTPAEUHHrw2By4VQQmnYIpmQ4DkJF5VzmtmRgb/NvoFhYdi/ikTOST4JTpYCAoJKZglDyVAjB4vderU1uepwvSgWPjFLxRmt+DUEogJiS6p5by1oDuYIrAqQZghBIMic1Li0DTqX4NmcFJzEJ2wtqylFyDH0S2BGA4bu2HlMGU0SXoXRHbFuWOpyAlwojSaZZjZ7lAHw7hYHkC8CmYqQSCWlAKq9H6pn/ND3zbUK4qwoYGWHmIUkgiuSDaXXMBa8XVGCxAtM7mm+TMMlAg4ELn7+LuSKcKEhDwLTpg=%
Noneref_PCollection_PCollection_6"%
Noneref_PCollection_PCollection_7*DWriteToText/Write/WriteImpl/DoOnce/FlatMap(<lambda at core.py:3228>)2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2t
beam:display_data:labelled:v1S
Transform Function<lambda>2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
ﬁ
?ref_AppliedPTransform_WriteToText-Write-WriteImpl-GroupByKey_22ö
 
beam:transform:group_by_key:v1&
Noneref_PCollection_PCollection_12"&
Noneref_PCollection_PCollection_13*&WriteToText/Write/WriteImpl/GroupByKey
√
Fref_AppliedPTransform_ReadFromText-Read-Map-lambda-at-iobase-py-898-_5¯
»

beam:transform:pardo:v1¨

©

 beam:dofn:pickled_python_info:v1Ñ
QlpoOTFBWSZTWQduVwYAAk5/4H///2lY8551DWvfgr//3/57xE4AUAMujUJym3cBKERMFPQTCbVPUaNqeiaDIPKeoeo00/Uj0m1DIA2ptQZNAGppHqMmmkyGhGRoA9QA0GgAAAAANAABpkiaNTEo/Umh6JoB5TR6nqAyGgDQAAwgA9QD9UGmqNSaeo0yYAJoDIwEaYjTTJpoAwIwRkHqBpg4GgNBo0DJoADQAGJoaaBpoAaNGgAaNIFTDhDg/RyZnnkMTIZuflWV7HKofn9txKkcqDCqiDLLBEJCBqCshJCE3LuopRGzmEMoH5ACtflYFIX8GdJmPosIzPVZPhS43FqBv8H1fHJoJDKPrejOee1Zfl6WUnho+e14Ud6eSFLN67i7ZfNU3xhyX3mlF7EcaoPGaxocBxUz43iBNpX5cnH7o7edteuFuiVlgAkvtep3YKd6mvfmrbsU1NrbidRFKGlOnnm0TcWSZ70e81IcD0ue7WpOWQ+oIEywLFoTpkz40hAkqwmbMcPr4dw1qlmTDsEFidLUVpo+zt6BdQjgAsoK6IxkE/DYqRPsCUHAAGkFUMQKFyXCFGbqHmGFUYqQiWt5DgWRE5gkwMYb7kQjjoCQSxpjpgBQMU0vGRo76IAgQoLJ+BLHUhj8YcM0aLUgoUgTIoNDBGIAYT4L9g88IUxuLVPMzLlXOebpEwEH5mCkh3nq7NxIK41bKQEkjvr71efHnd2uOhAqouBk6hQc0RcHaNaUsXHF6SKXAwSK/C7AHq16CEXpwpiq4B5NMx5qxcHK+suoumbNSZrM12uKTzrjxM5KFFjxAhWEAHiuaCnJcXAhFzSHZyweIQaQ1QjKPhg31mhEbFbHf6YcERRGJMNmsaV2KtU+W9OS1FNMDrlrmSN6tASsJ4Md2GzEse0t3bnWDolwvQFgaARnVYBxNPevYDIimDaqcmJQiCAdGxPaQ+Mct6di1SGhcMLKS1JhOx6HAe0SOFxN3ev8754WxFGobtUEh1NT3rA1V7eFpmIZ8EsgiEiBOWh2Z9QIkDK9QQbRKo5b1gNkk6o1SAJLITurE+T7bEBQkmPIwiqShbGvE7QBs+QU1NGgfFHZUUXIDJCRXSyMGmvfXZLJRgppHBVAvAgukQIQQSwOIovkgDnVJpLC8sw2b/4w7oTA8HHwh+5Sx5rhlQkZ34L2LuyQCVVmAWKrnQAhkKaiV7TN5oeWWYqtIWXNBUzApVFVyqhA24YGR5g3kKATk0Z2k6E3rCChmKoKOt/xdyRThQkAduVwYA==%
Noneref_PCollection_PCollection_1"%
Noneref_PCollection_PCollection_2*0ReadFromText/Read/Map(<lambda at iobase.py:898>)2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2t
beam:display_data:labelled:v1S
Transform Function<lambda>2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
∏
*ref_AppliedPTransform_WriteToText-Write_11â
H
#beam:transform:generic_composite:v1!<Write(PTransform) label=[Write]>4ref_AppliedPTransform_WriteToText-Write-WriteImpl_12%
Noneref_PCollection_PCollection_5"&
Noneref_PCollection_PCollection_16*WriteToText/Write:%ref_Environment_default_environment_1
Æ
@ref_AppliedPTransform_ReadFromText-Read-SDFBoundedSourceReader_6È
j
#beam:transform:generic_composite:v1C<SDFBoundedSourceReader(PTransform) label=[SDFBoundedSourceReader]>\ref_AppliedPTransform_ReadFromText-Read-SDFBoundedSourceReader-ParDo-SDFBoundedSourceDoFn-_7%
Noneref_PCollection_PCollection_2"%
Noneref_PCollection_PCollection_3*(ReadFromText/Read/SDFBoundedSourceReader:%ref_Environment_default_environment_1
ó
)ref_AppliedPTransform_AppliedPTransform_1È$ref_AppliedPTransform_ReadFromText_2%ref_AppliedPTransform_ConvertToDict_8"ref_AppliedPTransform_Prediction_9$ref_AppliedPTransform_WriteToText_10*)ref_AppliedPTransform_AppliedPTransform_1:%ref_Environment_default_environment_1
©
;ref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce_13È
â
 beam:transform:pickled_python:v1‰QlpoOTFBWSZTWUQEtKYAAEJ34G0IiCgAIQkAQAK/b90CYMQOAiAAioaFPSTTRo8kAGm1DepDepBpQyaDQaA0ADQAzMksRv3UyDlfgD6Ud12Si1NInuwFc4BuXPstY93hJTLbIHa3IIWJBGwhw3S+mLcMduQYJWolIbOWQarcDxptR7yFWtLcdMIpZwOQRiqgvgxkyE5fcsXeKi2iSKHz/F3JFOFCQRAS0pg=Cref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce-Impulse_14[ref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce-FlatMap-lambda-at-core-py-3228-_15Gref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce-Map-decode-_17"%
Noneref_PCollection_PCollection_8*"WriteToText/Write/WriteImpl/DoOnce:%ref_Environment_default_environment_1
à
$ref_AppliedPTransform_ReadFromText_2ﬂ
V
#beam:transform:generic_composite:v1/<ReadFromText(PTransform) label=[ReadFromText]>)ref_AppliedPTransform_ReadFromText-Read_3"%
Noneref_PCollection_PCollection_3*ReadFromText:%ref_Environment_default_environment_1
∏

9ref_AppliedPTransform_WriteToText-Write-WriteImpl-Pair_21˙	
ÿ
beam:transform:pardo:v1º
π
 beam:dofn:pickled_python_info:v1îQlpoOTFBWSZTWWMeOD8AAU7/4H3/XglJY4wlDWucgr//33ZrxA4AQAH7sd2512CUUaJPBT1DQ0eU9I9NQZBoGm1PUZBoDQ9QAGiaGppoT1NQPUGgBoAAAAAAAeoJU9JJknlAAyBpoA0GCZB6hoeoDR6nqMgEpqTIpskD1NG1GQBo0NABkaAAeoaAaPTuAMN/E0ts4YQloxxwHY/bU9ED5HCEgjTkgGQlInAhJGHDZVCMvTcW0dhuHh6nl6QHEb2iC9fg7Wd5SMylnCaDR4bk/EMc9YpM/gvFBSKNGsakMLzeIVlpFXVraYnYqIjz9zJnEuYmjXZVwTBhp85suB2xSpVVA3CNFMC3q0SesoON9B26wxY+vIMisSjyMjc9iiMvsQv23m3GIXuG03nlPW6E1VwRhCw4iDrgv3ZCwWHRqkFDQdRBSSFRLZyRu0ewwpIpHrlw5thRCLGkNNqSHGW+JnN0M6Zdy7Xi0mkhNEWiU0ySNSh267bSqa5AK5IPmaRHkshPHsTFiD3ZU7sQgNqCe+sPIpHwExIdY5R0xFMriXOtUA+di/MZk/BkMUny2aKCCtix2qlygslFBAwOJ2VQTUmHCJqGZjxERGUHqJWI9rKDbIMwxOVYxVR9dM4iCBo55Gm2NcROaUdglrleqW8EGEoBt3CZquPjPiekzLpROh1qFrKIkG6Ieo09CSV2Bhx8/2I/BlnTOdIZL7VtI0QmMBwmGizOQBMY2Fav86+HC3Tz4KSyQRogbjuuaelRKoTBGnSfH/i7kinChIMY8cH4&
Noneref_PCollection_PCollection_11"&
Noneref_PCollection_PCollection_12* WriteToText/Write/WriteImpl/Pair2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2t
beam:display_data:labelled:v1S
Transform Function<lambda>2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
î
1ref_AppliedPTransform_ReadFromText-Read-Impulse_4_

beam:transform:impulse:v1"%
Noneref_PCollection_PCollection_1*ReadFromText/Read/Impulse
¯
Gref_AppliedPTransform_WriteToText-Write-WriteImpl-DoOnce-Map-decode-_17¨
Ä
beam:transform:pardo:v1‰
·
 beam:dofn:pickled_python_info:v1ºQlpoOTFBWSZTWVPNHZkAAaH/8v3/2ClJY4glDW/civ//32ZrxA4AYAAIAAIAQAJOuuO07t3cNEE0UMTxNQzJHpMnpAADR6aRo0Bo0NlAyBok9GqeQjIyhoZDRoADIAAAAAAA1U/0VPKYjJHoIY1D1BmphAAYhoABoBoekEokxQTyTyhhqPSANBpp6gaAAADIaAAkyTIBR63+GQ05cuZsYFUfjTHKTZLR/JSPnuQVMgZGZAMYxAVWKjlCBfDrKgvj5PD9y1mUrqXFCibBev0wagL+FEk1ATdU4xDpDHx0B4QPYrknFDChp169kXEvfzotcSmSqi5DDtRX1TvKxBCfhEHVBGoAD47M3GYI3hoOvFomZLst7Ham96zHJjGffhQmmEB/QfRvTkIDFmqLQuclIg3uLHXg5egJMvW8krt9BdW8hCe9l5NXVlVVAEde5ODcpeoNEg0kVWPfZrCK+IMIg+2b5BBp2hQVNAtCW0xjiDggOsQUou1SoifEynK2emYNcAN8NjVoQu90QNs0RpQL5yAwk9YxxtmOazEZJdnYDF7lAyCqhZhILApIX68KmcygGnbZUjLHEqsNVKWxZdAqCUxXG6t2OCAV2LNCoENOBYK2K1ylYoOGsowOR4ojS2MVunJawrENjVxhFFSvAEkTUNSoMhdPIhePdJhXKhViar8+lalLhLKOMDCNKzKYdVqDMLgBBUglr6ooKpF6QCAagYKFd4QzwxyalFhsDbAZRZECgEQYtR0a1KaskocA4XMcKZZvMDGYKXWxTlJYSMt4HoKLSoBy3XwpEpHho+BqgxQ86TETbeycwTDISLNAwrw0KWYMwZrjaSQKfN9i7+pI9L6aakOrbZK5KqFEUIpKtedGsUIkOwY2BBK7/IGUQ1o0ZXZGyLAPsTx6Ls45p2nO9jUOvUlokkhATBymw9NSu8X9/i7kinChIKeaOzI=%
Noneref_PCollection_PCollection_7"%
Noneref_PCollection_PCollection_8*.WriteToText/Write/WriteImpl/DoOnce/Map(decode)2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2r
beam:display_data:labelled:v1Q
Transform Functiondecode2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
â
%ref_AppliedPTransform_ConvertToDict_8ﬂ

Ã
beam:transform:pardo:v1∞
≠
 beam:dofn:pickled_python_info:v1àQlpoOTFBWSZTWfQmnz4AAWH/8H//WQlBY+11H+u/hr//32ZrxA4AYABAAg6LNakGppqGpphTE0aYnqPU00aaNNGgNG0jQw1PUGmRp6mQGg1MRNBpRp6Go2iBmoAaAAAAaAA0AD1DmTTQyABiMgyAGmCBiAaNNABkDQANNU9ERM2qZqepp6RkGQA00aNAAAaNNAAeoAMgwVcD++qgv5MHQK5su/bSFoc6R8r5X++STIXu9yxjTXTmIX/W8IkBBKC4QWPABSA+YCwsH7XIxiKpsFL1y1b9Pcc7GMSIzXBIVDlgtYrjSnsk647fant0eGfQxsCxFA/sJV8RecclT0EoVheBBMscl6nRLwBHTQktrKk2is4ZZoCHBvTZkWfZNjdcRYFQR611miUlCivYIVn6rVVUjAQhcZbWWcBi0uXNmAdzWxoCxPSCkwXb2MsL78CMc3oy56pqmpXmrRaBKGOqPpORzbNkQWZA6FsIrk4IySnWpgqxRY6ngsFGpqkeI2niRHcRiBBYI6i3IV2lolnAhLKfadaEVxbyjUZTXfFFVFWHCUTeFSgh0hSGKQqYqoeujpeMPUFNiXWMYSbFKU/NspeYXTOmpBshikWc4KBF34YYQ2pOTQShBcBk9t3ZY3W4plQiqobzhNitUE8flMQFpAjWF+lm31VbAkkDRK8IkdEs4FFIefE8nzxnB2KJ3pSfF9WR9Zrp0gjyA2xqqTBowVtq3rhGAwVpJggKZ90EOhjSsJtWMuFMU6GjK1AS2QyHUfNkhyUY8BjGEPFEGkrFslEUgY4IU+5UgkEqQglmf3kIf1Ck+mvWn7TaHxQajQEj8JCwcBzEvAIUQfzzGCGixOkL6n6VEUbWuJLyMoCkYsinbJJFAFsKkWpey/4u5IpwoSHoTT58%
Noneref_PCollection_PCollection_3"%
Noneref_PCollection_PCollection_4*ConvertToDict2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2z
beam:display_data:labelled:v1Y
Transform Function_to_dictionary2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
°,
Bref_AppliedPTransform_WriteToText-Write-WriteImpl-FinalizeWrite_25⁄+
ä&
beam:transform:pardo:v1Ó%
ï
 beam:dofn:pickled_python_info:v1QlpoOTFBWSZTWdbMRU4AAYp/4H/8+yhff94QPWndgr/v3/JixA4QQAIdLVsaBBCU9TZE9T0RtBNpPU00D1MNBiTRghhG1M1NGmCYNJkin6m00RNqbQgNAMTEZADQAMgGQAYcDQaZDTRoYQMhoYI0NMmjQDIMQABoMRCjE0nqnmhJsk09NTyj1ANDygA0NABtJo9Ro9I6PBzJudzrQPuRBSJASzFtmMoCj58Y0iGRAWbMxYwotZKrePKssJD9ERAc/I9XPCDgqvyHjPvjx01iNCwCIG1wC+BDfXSOJlPip6wJwKOPoEXrztSxE4opHJ2gBgomMwXWJHwXg/GoLKNROF8UJDi+n4MiYASwD0Dh9XD05XQaduiq5KsceGQNIvVBqKwI8oi2ag5unMmrbMSzGVNrmOCMOQzmaDYCSgV0TXyaxB7yjBLXLATPcmaSbOnU8QkCoxuxChqVRWVnIckT88LlE/gkMCBThQO5fiEZXr19O2dCCyiJsSlLk9oRVwZQCUtDByhbaZDNSVQK8QIyoKzCTLPPNPaZBH6ZMiabbq6MQJ4yclG2GLp9FoRSjMBuMyAhYg4EN4ZnuLiQy6rYe1tHvZhicRE+Fx9XOG7R2dFInleJr1jeWIIGbckGlk0tbnGOOJxyxmBrpLvyNjRsxGRnRmRHVFdqFOQPwpg7tPJKVjBxLc854Qgz+aLjMV41zqetUzXwwSwIhTX46DVCCB9OGyO4X2sYE+/QBgv1GlUTB7mlxfqRrGecAcr3AIqf4ABiNG6w5EL/+TDOuBSX5QLumIZAMzAH+AfvYR0MX95pZhj2DZCVi/meauhyKLFO+1ueZ90J4MEmy5Q01miLPVbjKEVsTn28//F3JFOFCQ1sxFTgª
<python_side_input0-WriteToText/Write/WriteImpl/FinalizeWrite˙

beam:side_input:iterable:v1å

#beam:view_fn:pickled_python_data:v1‰	QlpoOTFBWSZTWR0QNR0AAij/8////y56Z4slD6tdgP//37f71A4EYAAAQBAIAAHAAxbnKR0RddhqaEU9NPSmGpiGNE2k002oGg0ZGhoZNANGjQAyZANA1NKYKflMNE1HqPTU0MmhoA0eoAAAAAA0eoNAAgJU21T9U0NMhhGQNNAxGBAxAaABoaGCNBhlDCU0giE8qb0k8mTQTTRoNNqaGjR6gNNAAAAA0AAXIUCyAItTp5M4TLiRfbAaYFexQeo28cM36k3kgGU+9BbCF2BjbFj+eBsb90BpeI871qBbEIMYwMcf5lopQGRA8WYoDRsfZDYlBBMd2MxMUIktNYHTtJePaXO9tVZH1xr9Z5L06Y03KNotM/5hkPzjRYm/SOmgJV7u57vfWpOOyooeI5by/hyRG7sfUjzKxOurQBdiw7jQDmriKc3qSYErQB+OSg9w6XhNXC/PwIDBYK7yAYKUCvt14OfYoWSlKC5jbUuWjIrec6lxXRYYh9newMyoy1sF47l7L1tWWNnvjchZK8MWnk2feJpjVWBx6C9KtWui2vGDY7mgqNCvQYhnywNTNsB4p99CErezKAAU8JAt39tAWEJFOjT00EMxcWSaKbFfxahzgGxXicgmMlk7mA55OTIoHrTmqNKCkQyxqChZ/G1rZqGlQPduF2NQUCQxscW1QECavj3LHmng+ffqwosF6FfMD52jGGp0Mjjovo1kD3RuXhhdOpgzvPmYiBRhR80LSu/TfMktAt4qWMfCsla11tJfrIZVJEZNI1g55TqDFW/NFRnyXyap0QzBKy5IZBmwQMsKB3kUiDApcSZDtOaJS6Kbc2Z4OG7IgQjJk2zFYqgyYGZMZ9b0VGPKz3nBoWca3bqN/bI6LNIujfCe2IjFt4PjNDaSgama07DNtQrJa0CwslineU1eEFwg4x0FkhtDlwTIs0zU4RQjtSU0l04FRZpROEyqzlvlmlKGVCJxE4A7boIzBB6SmsNWF+fSBWiW2A3AEJcDiY67kvGCnNOz3Y2gYqjd3HAIHgy+dRE2/sOIAIj7rCGId5kHlJITcycVbdUdM093QNFDeD/ZmmzUcu3WIULVo36G+y3JuzbaClDMJRASXEQs8kQ0JHRgZnEIBwiEBum5Ctg+cUIuNOm9OktTkUidIiUFP4duGGFfu0hrkkY5cOOvGqanlRynciTRSwU5OdUZQ+0mWGzqaYZbJJn5KJlK6CmfroUViRhdwyZn9gF3JFOFCQHRA1HQ…
(beam:window_mapping_fn:pickled_python:v1úQlpoOTFBWSZTWZSnr4UAACJ34EwAACAgAQgAAAC/596AQAQOACAASIp6mj1Bppk9TIHtU0FNT0jTQ9CYQNPTRDImBd0r8s9K9NNArxThgM2Te+1nSjF6nhKFjgpkLgI+ZCbAu3QmeGCU2TAu5IpwoSEpT18Kª
<python_side_input2-WriteToText/Write/WriteImpl/FinalizeWrite˙

beam:side_input:iterable:v1å

#beam:view_fn:pickled_python_data:v1‰	QlpoOTFBWSZTWR0QNR0AAij/8////y56Z4slD6tdgP//37f71A4EYAAAQBAIAAHAAxbnKR0RddhqaEU9NPSmGpiGNE2k002oGg0ZGhoZNANGjQAyZANA1NKYKflMNE1HqPTU0MmhoA0eoAAAAAA0eoNAAgJU21T9U0NMhhGQNNAxGBAxAaABoaGCNBhlDCU0giE8qb0k8mTQTTRoNNqaGjR6gNNAAAAA0AAXIUCyAItTp5M4TLiRfbAaYFexQeo28cM36k3kgGU+9BbCF2BjbFj+eBsb90BpeI871qBbEIMYwMcf5lopQGRA8WYoDRsfZDYlBBMd2MxMUIktNYHTtJePaXO9tVZH1xr9Z5L06Y03KNotM/5hkPzjRYm/SOmgJV7u57vfWpOOyooeI5by/hyRG7sfUjzKxOurQBdiw7jQDmriKc3qSYErQB+OSg9w6XhNXC/PwIDBYK7yAYKUCvt14OfYoWSlKC5jbUuWjIrec6lxXRYYh9newMyoy1sF47l7L1tWWNnvjchZK8MWnk2feJpjVWBx6C9KtWui2vGDY7mgqNCvQYhnywNTNsB4p99CErezKAAU8JAt39tAWEJFOjT00EMxcWSaKbFfxahzgGxXicgmMlk7mA55OTIoHrTmqNKCkQyxqChZ/G1rZqGlQPduF2NQUCQxscW1QECavj3LHmng+ffqwosF6FfMD52jGGp0Mjjovo1kD3RuXhhdOpgzvPmYiBRhR80LSu/TfMktAt4qWMfCsla11tJfrIZVJEZNI1g55TqDFW/NFRnyXyap0QzBKy5IZBmwQMsKB3kUiDApcSZDtOaJS6Kbc2Z4OG7IgQjJk2zFYqgyYGZMZ9b0VGPKz3nBoWca3bqN/bI6LNIujfCe2IjFt4PjNDaSgama07DNtQrJa0CwslineU1eEFwg4x0FkhtDlwTIs0zU4RQjtSU0l04FRZpROEyqzlvlmlKGVCJxE4A7boIzBB6SmsNWF+fSBWiW2A3AEJcDiY67kvGCnNOz3Y2gYqjd3HAIHgy+dRE2/sOIAIj7rCGId5kHlJITcycVbdUdM093QNFDeD/ZmmzUcu3WIULVo36G+y3JuzbaClDMJRASXEQs8kQ0JHRgZnEIBwiEBum5Ctg+cUIuNOm9OktTkUidIiUFP4duGGFfu0hrkkY5cOOvGqanlRynciTRSwU5OdUZQ+0mWGzqaYZbJJn5KJlK6CmfroUViRhdwyZn9gF3JFOFCQHRA1HQ…
(beam:window_mapping_fn:pickled_python:v1úQlpoOTFBWSZTWZSnr4UAACJ34EwAACAgAQgAAAC/596AQAQOACAASIp6mj1Bppk9TIHtU0FNT0jTQ9CYQNPTRDImBd0r8s9K9NNArxThgM2Te+1nSjF6nhKFjgpkLgI+ZCbAu3QmeGCU2TAu5IpwoSEpT18K◊
<python_side_input1-WriteToText/Write/WriteImpl/FinalizeWriteñ

beam:side_input:iterable:v1®
#beam:view_fn:pickled_python_data:v1ÄQlpoOTFBWSZTWevwyHMAAIR/4HTzUAAAY4glCgscAL//3yZDBA4AMADERBNIE9IGmj0T0QNNA0yAeoMg1NAgxJoZPUBoaAAaBpoBgAAAANAAAAABEKw87hknW4MTzjfogD5DPaKy3zV2GnwgNjXOMXa6iapkp5GSSkgItRcCEUzRwNBAbeeI6KaXrHia0WtPQCg11VmpXmk4omI1aFZ06Gyruk5DfTphvCYxdhR6NeiccmyFVRSQrDGQ2jMiSN71Qwd3W42PDSUICNOlJ1nwIXU94W6dg72CCSkic6IpwhWNSMROaTJVxBQua6lid9kkwsYcVxzFkBgh5B0IxH5cdp/rUpvhcCHRzixdLIXSlJ/NBAUf8XckU4UJDr8MhzA=…
(beam:window_mapping_fn:pickled_python:v1úQlpoOTFBWSZTWZSnr4UAACJ34EwAACAgAQgAAAC/596AQAQOACAASIp6mj1Bppk9TIHtU0FNT0jTQ9CYQNPTRDImBd0r8s9K9NNArxThgM2Te+1nSjF6nhKFjgpkLgI+ZCbAu3QmeGCU2TAu5IpwoSEpT18K]
<python_side_input0-WriteToText/Write/WriteImpl/FinalizeWriteref_PCollection_PCollection_9^
<python_side_input1-WriteToText/Write/WriteImpl/FinalizeWriteref_PCollection_PCollection_14^
<python_side_input2-WriteToText/Write/WriteImpl/FinalizeWriteref_PCollection_PCollection_15%
Noneref_PCollection_PCollection_8"&
Noneref_PCollection_PCollection_16*)WriteToText/Write/WriteImpl/FinalizeWrite2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2{
beam:display_data:labelled:v1Z
Transform Function_finalize_write2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
ö	
<ref_AppliedPTransform_WriteToText-Write-WriteImpl-Extract_23Ÿ
¥
beam:transform:pardo:v1ò
ï
 beam:dofn:pickled_python_info:v1QlpoOTFBWSZTWeBfQiYAAPV/4H39WihAY8olDW+cgr//32ZjhA4AMAF6bRA1EyahoaABkNAGgwQGgADQADU0nolPxTTaaKep+knqGgAADTIaA0HqAA1PSmENIynqNNNNNNPUbUaA0ANAAZpA8ohViE+ajh6GD9O/CkDtCZQCFRFQUhkIrVaOEjtp8vgenFNIIOYOnTg1tyORcLGyrTZP0jT5NujUaK+Zf9SJiKqgixTPlIBEsaVQtCEyAHAcd3r4HUOFDzyhlgkG1CswEDEFdpQBF0+jF05DXgGcJJ5/W6cchgcOkaUC5tqwyB60t+drGWFQxT9ma9eL8gDVg2gLgatxeas6BAXuR4trI0j4XHY8hUHgUyiai89hDAvCupGKmLgSqW35h3lVoVvdnqkTQUpoESM6TkWaiQKiuXmkGZqQ3YtiDgjwdXDdeB4/CLCUQFUy8LNeNsYquTAEwhMQUHFLqrDnailh8ZFmm8RvCa2iFksDZ4hGAsYcAYVcvmZ9pt8R3Rdky1MUCWDgzvEktuBURCkxoGECgFWYqQkhZAFVn5yJXN9ra2/XY6EIIIGjcJBFleIWbtDmDAgpnjKzMxZpeyWWELkI0f4u5IpwoSHAvoRM&
Noneref_PCollection_PCollection_13"&
Noneref_PCollection_PCollection_14*#WriteToText/Write/WriteImpl/Extract2ç
beam:display_data:labelled:v1l
Transform Function/apache_beam.transforms.core.CallableWrapperDoFn2fn:!apache_beam.transforms.core.ParDo2t
beam:display_data:labelled:v1S
Transform Function<lambda>2fn:/apache_beam.transforms.core.CallableWrapperDoFn:%ref_Environment_default_environment_1
˘
)ref_AppliedPTransform_ReadFromText-Read_3À
Â
beam:transform:read:v1 
≈
beam:source:pickled_python:v1£
†QlpoOTFBWSZTWfSfIfUAAOF/4F9d+mBQY55QCAtfAL/v3/JiRA4AMAFCyUQU0ajR6gAADJo0bUBo0GjTJoA0GjVMjKbRG0oAYg0APUaaBpoyBtQA01CZIMQ00TNTQwmgBoYRppiYaE9CIWWQWN8kL0QCIGKQQeY5PwnUCAwPJbiVXTlcUS+fRSAAfKZkY4RPtSxWhxZm23ZcTh0HJLCTTwLPUm6UUZUB1RZVHFM6RiqLru63CS6Eao74xEDBuzVarVCmuKE4QQFglkKKCuCCIsDIS1ovUpSxK5wOS6QrSBu3I68E9XWhlMBTIW0McI2V3wIEL/UG1BYglIaV0LTBtjc55C/Ytw7pZCF1agFAoxgMoJEigsouFTVOTUQwmtE07XB6MimlIzI6Ngg6JHRAW8KjIR8ETuIaoFCvvgwgiqCFzkSwtnuVE1V2smqcXQoD5nsSbTijrAbQIoD34vdorSIFInSbShCf80SwoqIhGtZMzJnKROInSzEJUJneqzoxrXGe0qQNlG8wELj/xdyRThQkPSfIfUA=1ref_AppliedPTransform_ReadFromText-Read-Impulse_4Fref_AppliedPTransform_ReadFromText-Read-Map-lambda-at-iobase-py-898-_5@ref_AppliedPTransform_ReadFromText-Read-SDFBoundedSourceReader_6"%
Noneref_PCollection_PCollection_3*ReadFromText/Read2u
beam:display_data:labelled:v1T
Read Source!apache_beam.io.textio._TextSource2source:apache_beam.io.iobase.Read2ê
beam:display_data:labelled:v1o
File Pattern.gs://cloudcomputing-345522-gs/input/images.txt2file_pattern:!apache_beam.io.textio._TextSource2i
beam:display_data:labelled:v1H
Compression Typeauto2compression:!apache_beam.io.textio._TextSource2o
beam:display_data:labelled:v1N
Strip Trailing New Lines2strip_newline:!apache_beam.io.textio._TextSource2a
beam:display_data:labelled:v1@
Buffer Size(Ä@2buffer_size:!apache_beam.io.textio._TextSource2z
beam:display_data:labelled:v1Y
Coder&apache_beam.coders.coders.StrUtf8Coder2coder:!apache_beam.io.textio._TextSource:%ref_Environment_default_environment_1â
ref_PCollection_PCollection_6h
142WriteToText/Write/WriteImpl/DoOnce/Impulse.Noneref_Coder_BytesCoder_1"ref_Windowing_Windowing_1§
ref_PCollection_PCollection_7Ç
K68WriteToText/Write/WriteImpl/DoOnce/FlatMap(<lambda at core.py:3228>).Noneref_Coder_BytesCoder_1"ref_Windowing_Windowing_1å
ref_PCollection_PCollection_14j
*35WriteToText/Write/WriteImpl/Extract.Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1ö
ref_PCollection_PCollection_2y
748ReadFromText/Read/Map(<lambda at iobase.py:898>).None!ref_Coder__MemoizingPickleCoder_3"ref_Windowing_Windowing_1r
ref_PCollection_PCollection_5Q
10Prediction.Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1x
ref_PCollection_PCollection_1W
 25ReadFromText/Read/Impulse.Noneref_Coder_BytesCoder_1"ref_Windowing_Windowing_1ñ
ref_PCollection_PCollection_8u
546WriteToText/Write/WriteImpl/DoOnce/Map(decode).Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1í
ref_PCollection_PCollection_16p
041WriteToText/Write/WriteImpl/FinalizeWrite.Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1ù
ref_PCollection_PCollection_10{
;52WriteToText/Write/WriteImpl/WindowInto(WindowIntoFn).Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1ê
ref_PCollection_PCollection_15n
.39WriteToText/Write/WriteImpl/PreFinalize.Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1j
ref_PCollection_PCollection_4I
13ConvertToDict.Noneref_Coder_MapCoder_7"ref_Windowing_Windowing_1á
ref_PCollection_PCollection_13e
-38WriteToText/Write/WriteImpl/GroupByKey.Noneref_Coder_TupleCoder_10"ref_Windowing_Windowing_1≠
ref_PCollection_PCollection_3ã
K68ReadFromText/Read/SDFBoundedSourceReader/ParDo(SDFBoundedSourceDoFn).Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1ì
ref_PCollection_PCollection_9r
243WriteToText/Write/WriteImpl/InitializeWrite.Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1Ä
ref_PCollection_PCollection_12^
'32WriteToText/Write/WriteImpl/Pair.Noneref_Coder_TupleCoder_8"ref_Windowing_Windowing_1ë
ref_PCollection_PCollection_11o
/40WriteToText/Write/WriteImpl/WriteBundles.Noneref_Coder_FastPrimitivesCoder_6"ref_Windowing_Windowing_1ï
ref_Windowing_Windowing_1x
"
 beam:window_fn:global_windows:v1ref_Coder_GlobalWindowCoder_2": (08HZ%ref_Environment_default_environment_1"ﬂ
ref_Coder_FastPrimitivesCoder_6ª
∏
beam:coder:pickled_python:v1ó
îFastPrimitivesCoder$eNprYJmaxgABPZKJBYnJGanxSamJuXrJ+SmpRcVQakqPsFticUlAUWZuZklmWWqxM0h4yuQpmo1Taqf08MenJebkJCUmZ8eD1U/JYOjhDshMzs5JRVGYVJykBwDOUCqY"@
ref_Coder_GlobalWindowCoder_2

beam:coder:global_window:v1"Y
ref_Coder_IterableCoder_11;

beam:coder:iterable:v1ref_Coder_FastPrimitivesCoder_6"˘
ref_Coder_MapCoder_7‡
›
beam:coder:pickled_python:v1º
πMapCoder$eNprYJm6jAECeiQTCxKTM1Ljk1ITc/WS81NSi4qh1JQeDt/EAmcQe8rkKZqNU2qnaPRwxWenVsaDFUzJYOgRdkssLgkoyszNLMksSy1GUdzDH5+WmJOTlJicjdDAHZCZnJ2TiqIwqTiphye+LDGnNBWmkB0skcGVwVucVJqkBwC8wkO0"Ö
ref_Coder_TupleCoder_4k

beam:coder:kv:v14ref_Coder__SDFBoundedSourceWrapperRestrictionCoder_5ref_Coder_FastPrimitivesCoder_6"}
ref_Coder_TupleCoder_8c

beam:coder:kv:v1,ref_Coder_DeterministicFastPrimitivesCoder_9ref_Coder_FastPrimitivesCoder_6"Â
,ref_Coder_DeterministicFastPrimitivesCoder_9¥
±
beam:coder:pickled_python:v1ê
çDeterministicFastPrimitivesCoder$eNp9i7EKwjAYhDu4OYg4uTmJLu07qCji0qHgGJL4a3+atiFJxQ6C7tn8fT8fRW0FcfGGu+O479K5P4JWfsg1lykwATwPZbkDYz9BfrQABybHAq1DueTWxQZzdHgEO39/6EbTK51p4vusKl6DqrE4sIanNPCDP4zvsT1XSnCZfYFujDJT8HMUVvgusw40U1yAIj/eGnSQlAmcXNT01te5VtHKlJWe1RuoqRLhE2veW+s="1
ref_Coder_BytesCoder_1

beam:coder:bytes:v1"y
ref_Coder_TupleCoder_10^

beam:coder:kv:v1,ref_Coder_DeterministicFastPrimitivesCoder_9ref_Coder_IterableCoder_11"”
!ref_Coder__MemoizingPickleCoder_3≠
™
beam:coder:pickled_python:v1â
Ü_MemoizingPickleCoder$eNprYJnqywABPZKJBYnJGanxSamJuXrJ+SmpRcVQakqPaLxvam5+ZlVmXnpAZnJ2TqozSGLK5CmajVNqp/RwJYN1FmdWpU7xFihO0gMAF4If5g=="Å
4ref_Coder__SDFBoundedSourceWrapperRestrictionCoder_5»
≈
beam:coder:pickled_python:v1§
°_SDFBoundedSourceWrapperRestrictionCoder$eNprYJnqwwABPaKJBYnJGanxSamJuXqZ+UCUlFicOqVHIz7Yxc0pvzQvJTUlOL+0KDk1vCixoCC1KCi1uKQoM7kkMz/POT8ltWjK5CmajVNqpyTpAQDfLx+4*Ú
%ref_Environment_default_environment_1»beam:env:docker:v1/
-gcr.io/cloud-dataflow/v1beta3/python39:2.37.0*beam:coder:bytes:v1*beam:coder:string_utf8:v1*beam:coder:kv:v1*beam:coder:bool:v1*beam:coder:varint:v1*beam:coder:double:v1*beam:coder:iterable:v1*beam:coder:timer:v1*beam:coder:interval_window:v1*beam:coder:length_prefix:v1*beam:coder:global_window:v1*beam:coder:windowed_value:v1*"beam:coder:param_windowed_value:v1*#beam:coder:state_backed_iterable:v1*beam:coder:custom_window:v1*beam:coder:row:v1*beam:coder:sharded_key:v1*#beam:protocol:progress_reporting:v0*)beam:protocol:harness_monitoring_infos:v1*beam:protocol:worker_status:v1*beam:combinefn:packed_python:v1*6beam:version:sdk_base:apache/beam_python3.9_sdk:2.37.0*1beam:transform:sdf_truncate_sized_restrictions:v1*beam:transform:to_string:v1* beam:protocol:sibling_workers:v12“
beam:artifact:type:url:v1{
ygs://cloudcomputing-345522-gs/staging/beamapp-djcoralde-0329115208-825877-embfshim.1648554728.826022/pickled_main_session beam:artifact:role:staging_to:v1"
pickled_main_session2ÿ
beam:artifact:type:url:v1~
|gs://cloudcomputing-345522-gs/staging/beamapp-djcoralde-0329115208-825877-embfshim.1648554728.826022/dataflow_python_sdk.tar beam:artifact:role:staging_to:v1"
dataflow_python_sdk.tar2»
beam:artifact:type:url:v1v
tgs://cloudcomputing-345522-gs/staging/beamapp-djcoralde-0329115208-825877-embfshim.1648554728.826022/workflow.tar.gz beam:artifact:role:staging_to:v1"
workflow.tar.gz2ê
beam:artifact:type:url:v1ö
ógs://cloudcomputing-345522-gs/staging/beamapp-djcoralde-0329115208-825877-embfshim.1648554728.826022/apache_beam-2.37.0-cp39-cp39-manylinux1_x86_64.whl beam:artifact:role:staging_to:v1"4
2apache_beam-2.37.0-cp39-cp39-manylinux1_x86_64.whl)ref_AppliedPTransform_AppliedPTransform_1")beam:requirement:pardo:splittable_dofn:v1